---
- name: add tomcat group
  group: 
    name: tomcat
  
- name: add tomcat user
  user: 
    name: tomcat
    group: tomcat
    home: /opt/tomcat
    createhome: no

- name: Create /opt/tomcat  home direct
  file: 
    path: /opt/tomcat
    state: directory
    mode: 0755

- name: Download latest tomcat using python script
  command: python /home/ansible/devops-tools-menu-driven/files/latest_tomcat_down.py 
  #script: /home/ansible/devops-tools-menu-driven/files/latest_tomcat_down.py
  #args:  
   # executable: python
  register: knowpath
#- name: Download
 # get_url:
  #  url: http://apache.cs.utah.edu/tomcat/tomcat-9/v9.0.22/bin/apache-tomcat-9.0.22.tar.gz
   # dest: /opt
- debug: msg={{ knowpath }}

- name: Unarchive the tar file
  unarchive: 
    src: /opt/apache-tomcat-9.0.22.tar.gz
    dest: /opt/tomcat
    extra_opts: [--strip-components=1]

- name: Change ownership
  file: 
    path: /opt/tomcat
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory

- name: Copy tomcat service from local to remote 
  copy: 
    src: tomcat.service
    dest: /etc/systemd/system
    mode: 0755

- name: Start and enable tomcat service
  systemd: 
    name: tomcat
    state: started
    enabled: true
    
   

